width: 1440
height: 1080
Offset_x: 0
Offset_y: 0
FrameRateEnable: true
FrameRate: 300.0
BurstFrameCount: 1
ExposureMode: 0
ExposureTime: 4000
GammaEnable: true
Gamma: 0.7
GainAuto: 0
Gain: 15.0
SaturationEnable: false
Saturation: 128
BalanceWhiteMode: 0
BalanceRatio_Red: 1611
BalanceRatio_Green: 1024
BalanceRatio_Blue: 2150
TriggerMode: 1
TriggerSource: 0
LineSelector: 99
